### ISSUE TITLE
Testy rejestracji na przykładowych danych

### ISSUE THREAD

**Issue by shipurjan** [TheKTM1/Plantasia#8]

**Comment by Kripsu** [comment]
![Testy rejestracji 1](https://user-images.githubusercontent.com/92221629/236899004-3f62be4c-a768-45e1-b959-4ab63e176af1.png)
![Testy 2](https://user-images.githubusercontent.com/92221629/236899011-ed0be8ed-0823-4c18-bdd6-09e13fd9963c.png)
Rejestracja działa, nie można dwa razy robić konta na tego samego użytkownika, hasło musi mieć minimalną długość, oraz znak specjalny, co jest przestrzegane. Jeśli hasło jest odpowiednie, a mail użyty po raz pierwszy to jest komunikat o udanej rejestracji
